# Generated by Django 5.2.7 on 2025-12-12 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('foto', models.FileField(blank=True, null=True, upload_to='tecnologias')),
            ],
        ),
        migrations.CreateModel(
            name='SitioWeb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('creador', models.CharField(max_length=150)),
                ('foto', models.FileField(blank=True, null=True, upload_to='logo')),
                ('tecnologias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SitioWeb.tecnologias')),
            ],
        ),
    ]
